# Generated by Django 4.1 on 2022-09-17 06:31

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched', models.BooleanField()),
                ('title', models.TextField()),
                ('rating', models.IntegerField()),
                ('release_date', models.DateField()),
                ('review', models.TextField()),
                ('the_json', jsonfield.fields.JSONField(default=dict)),
            ],
        ),
    ]
